language: android
jdk: oraclejdk8
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
script: ./gradlew --stacktrace lint test :Demo:assembleDebug :Demo:assembleRelease
